### ISSUE TITLE
Use ArgCheck.jl instead of @assert

### ISSUE THREAD

**Issue by itsdfish** [DominiqueMakowski/SubjectiveScalesModels.jl#9]
FYI, I noticed you use `@assert` in your constructors. It [turns out](https://discourse.julialang.org/t/efficient-use-of-test-or-assert/75895) that `@assert` should only be used for debugging. ArgsCheck.jl looks like a good alternative, which generates informative error messages by default. 

Also, in your constructor, you could simplify the type prompotion with `OrderedBeta(promote(μ, ϕ, k1, k2)...)` since you are not using `T` for another purpose.

**Comment by DominiqueMakowski** [comment]
Cheers for the suggestions

RE `@assert`, my old R/Python habits make me slightly concerned about adding a new external dependency for "this little", but I should probably work on that given that the package ecosystem seems more robust in Julia.

That said, it seems like there might be plans for adding this functionality into base: https://github.com/JuliaLang/julia/pull/41342
So I think I'll wait a bit to see what's up with that and will replace the current asserts with the other suggested base implementation using `throw` like in:

https://github.com/DominiqueMakowski/SubjectiveScalesModels.jl/blob/825f3fc089e64361e72e1a336003ea78320dc496/src/BetaPhi2.jl#L39-L41

**Comment by itsdfish** [comment]
No problem!

I think either approach is reasonable. One thing I consider when adding a non-critical dependency is whether it is lightweight. ArgsCheck.jl has no dependencies, and its code base is small. So it probably wouldn't have any unwanted side effects.  Nonetheless, `throw` and `error` are good choices. I'll go a head and close this. The package looks like its coming along well!
